### PR TITLE
Bugfix: Remove hostname for Jikan Search Query

### PR DESCRIPTION
**Pull request by kayneth**
## Pull request type

Please check the type of change your PR introduces:

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Currently there is a 400: Bad Request for Search Query. This is due to a use of `Url:href()` returning the full URL including the hostname. This is not compatible with the Fetch library. 

Issue Number: N/A

## What is the new behavior?

As we only need pathname and search parts, I've only extracted them.

## -

-

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by Julien-Broyard** [comment]
Thanks for taking the time to propose a bug fix ! I'll merge that tonight when I'll be home 😄

**Comment by kayneth** [comment]
> Thanks for taking the time to propose a bug fix ! I'll merge that tonight when I'll be home 😄

You're welcome! I was trying to implement this library with NextJS and it was the only blocking thing I encountered 😅

**Comment by kayneth** [comment]
@Julien-Broyard Do you have a new release scheduled? Or do you want to wait for v2?

**Comment by Julien-Broyard** [comment]
I'll try to release a fix for this on friday and then I'll work on v2.0.0

**Comment by kayneth** [comment]
> I'll try to release a fix for this on friday and then I'll work on v2.0.0

Hi 😄 
In case there is a problem or something you forgot: I saw the release on Github but nothing on NPM Registry.

**Pull request merged**
